export const nasty = [
    'Lights on or lights off?',
    'Hard and fast, or slow and sensual?',
    'Dominant or submissive?',
    'Morning sex or evening sex?',
    "What's your favorite sex position?",
    "What's a sex position that you've never tried that you're curious about?",
    "What's something unexpected that turns you on?",
    'Which do you enjoy more: oral or penetration?',
    'Would you rather have average sex every day or amazing sex once a month?',
    'Would you rather be with someone with no sexual experience or a ton of sexual experience?',
    'If you could hook up with any celebrity in the world, who would you pick?',
    'How often do you masturbate?',
    'What do you fantasize about when you masturbate?',
    'Do you like porn?',
    'What was your hottest sexual experience',
    'Would you ever have sex in a public place?',
    'Do you like the idea of getting tied up',
    "What's the favorite part about your body?",
    'Which part of your body do you want more to be touched?',
    'How do you like to be kissed?',
    'Do you have any kinks, fetishes, or guilty pleasures?',
    'What is your dirtiest sexual fantasy?',
]

// Scraped Online