export const normal: string[] = [
    "What's the best book you've read recently?",
    'If you could travel anywhere right now, where would you go?',
    "What's your favorite childhood memory?",
    "What's a skill you've always wanted to learn?",
    'If you could have any superpower, what would it be?',
    "What's your favorite type of music?",
    "What's the most adventurous thing you've ever done?",
    'If you could meet any historical figure, who would it be?',
    "What's your go-to comfort food?",
    "What's your dream job?",
    "What's the most interesting place you've been to?",
    "What's a movie you can watch over and over?",
    'Do you believe in aliens?',
    "What's the most embarrassing thing that's ever happened to you?",
    'If you could have dinner with any three people, living or dead, who would they be?',
    "What's your favorite way to relax?",
    "What's the last TV show you binge-watched?",
    "What's a hobby you've always wanted to try?",
    "What's the best advice you've ever received?",
    'If you could time travel, would you go to the past or the future?',
    "What's your favorite season and why?",
    'If you had a million dollars, how would you spend it?',
    "What's your favorite animal?",
    "What's the most meaningful gift you've ever received?",
    "What's a goal you're currently working towards?",
    'If you could switch lives with someone for a day, who would it be?',
    "What's the scariest thing you've ever done?",
    "What's a place you've always wanted to visit but haven't yet?",
    "What's a movie that always makes you laugh?",
    "What's your favorite thing about yourself?",
    "What's your idea of a perfect day?",
    "What's the best concert you've ever been to?",
    'If you could live in any time period, when would it be?',
    "What's a skill you're proud of?",
    "What's your favorite board game or video game?",
    'If you could only eat one cuisine for the rest of your life, what would it be?',
    "What's a topic you could talk about for hours?",
    "What's the most beautiful place you've ever seen?",
    "What's a song that always puts you in a good mood?",
    "What's something that never fails to make you smile?",
    'If you could have any job for a week, what would it be?',
    "What's the best piece of advice you'd give your younger self?",
    "What's the last thing you Googled?",
    "What's a language you'd love to learn?",
    "What's a childhood show you used to love?",
    'If you could eliminate one thing from your daily routine, what would it be?',
    "What's your favorite way to stay active?",
    "What's a weird talent you have?",
    "What's the most interesting documentary you've watched?",
    'If you could spend a day with a fictional character, who would it be?',
    `What's a place you consider your "happy place"?`,
    "What's your favorite type of exercise?",
    "What's the last dream you remember having?",
    'If you could invent something, what would it be?',
    "What's a movie that made you cry?",
    "What's a cause you're passionate about?",
    "What's your favorite thing to do on weekends?",
    "What's a place you'd love to live in?",
    'If you could master any instrument, which one would you choose?',
    "What's the most interesting fact you know?",
    "What's your favorite way to spend a rainy day?",
    "What's a fashion trend you never understood?",
    'If you could trade lives with anyone for a day, who would it be?',
    "What's your favorite memory from school?",
    "What's the last thing that made you laugh really hard?",
    "What's a book that had a big impact on you?",
    "What's something you've always wanted to ask me?",
    "What's your favorite app on your phone?",
    'If you could star in any movie, which one would it be?',
    "What's your favorite type of dessert?",
    "What's the best vacation you've ever been on?",
    "What's a goal you've accomplished recently?",
    'If you could meet any living celebrity, who would it be?',
    "What's the most challenging thing you've done this year?",
    "What's your favorite quote?",
    "What's the most interesting historical event to you?",
    "What's your favorite type of art?",
    'If you could have any animal as a pet, what would it be?',
    "What's a food you could eat every day?",
    "What's a movie that disappointed you?",
    "What's your favorite outdoor activity?",
    'If you could solve any world problem, what would it be?',
    "What's your favorite social media platform?",
    "What's something you're currently obsessed with?",
    "What's a skill you wish you could unlearn?",
    "What's the most important lesson you've learned this year?",
    'If you could attend any event in history, what would it be?',
    "What's your favorite way to stay organized?",
    "What's a habit you've been trying to break?",
    'If you could have dinner with a fictional character, who would it be?',
    "What's your favorite way to show kindness to others?",
    "What's a movie that surprised you in a good way?",
    "What's something you collect?",
    'If you could live in any era, which one would you choose?',
    "What's a song that reminds you of a specific moment?",
    "What's your favorite thing to do before bed?",
    "What's the most valuable lesson you've learned from a mistake?",
    "What's a country you'd love to visit someday?",
    'If you could only keep five possessions, what would they be?',
    "What's something you're looking forward to in the near future?",
    "What's a skill you wish you were better at?",
    'If you could have any animal talk to you, which one would it be?',
    "What's the most interesting job you've ever heard of?",
    'If you could have any fictional character as a best friend, who would it be?',
    "What's a goal you've had for a long time but haven't achieved yet?",
    'If you could witness any historical event, which one would it be?',
    "What's your favorite type of weather?",
    'If you could swap lives with anyone for a day, who would it be?',
    "What's the most unusual food you've ever tried?",
    'If you could instantly become an expert in something, what would it be?',
    "What's the best piece of advice you've given someone?",
    'If you could have any view from your window, what would it be?',
    "What's the most daring thing you've ever eaten?",
    'If you could only eat one cuisine for the rest of your life, what would it be?',
    "What's the most memorable birthday you've had?",
    'If you could be fluent in any language, which one would you choose?',
    "What's the best gift you've ever given someone?",
    'If you could relive any day of your life, which one would it be?',
    "What's a hobby you had as a child that you wish you still did?",
    'If you could have a conversation with your future self, what would you ask?',
    "What's the most spontaneous thing you've ever done?",
    'If you could have any mythical creature as a pet, which one would it be?',
    "What's something you'd like to be famous for?",
    'If you could travel back in time and meet your younger self, what age would you choose?',
    "What's a place you've always wanted to go but haven't had the chance?",
    'If you could create a new holiday, what would it celebrate?',
    "What's your favorite way to spend a Friday night?",
    'If you could spend a day with any celebrity, who would it be?',
    "What's the most meaningful compliment you've received?",
    'If you could master any dance style, which one would you pick?',
    "What's a movie you loved as a kid that still holds up?",
    'If you could have any job for a week, what would it be?',
    "What's the most unique hotel or Airbnb you've stayed in?",
    'If you could learn the answer to one mystery, what would it be?',
    "What's something you're always curious about?",
    'If you could be a character in any video game, which one would you choose?',
    "What's a place that feels like home to you?",
    'If you could have any historical artifact, what would it be?',
    "What's the best decision you've ever made?",
    'If you could instantly become an expert in any instrument, which one would it be?',
    "What's a song that describes your current mood?",
    'If you could have any vehicle (real or fictional), what would you choose?',
    "What's the most unusual talent you've seen someone have?",
    'If you could have a conversation with any animal, which one would you pick?',
    "What's a subject you wish you knew more about?",
    'If you could have any fictional technology, what would it do?',
    "What's a movie that scared you as a child?",
    'If you could learn a new sport overnight, which one would you choose?',
    "What's the most inspiring quote you've heard?",
    'If you could be friends with any historical figure, who would it be?',
    "What's the most memorable event you've attended?",
    'If you could be a character in any book, which one would you choose?',
    "What's the best way someone has shown kindness to you?",
    'If you could visit any planet in our solar system, which one would it be?',
    "What's something you've always wanted to invent?",
    "If you could spend a day in someone else's shoes, who would it be?",
    "What's a lesson you've learned from a difficult experience?",
    'If you could visit any famous landmark, which one would it be?',
    "What's the most fantastic thing you've seen in nature?",
    'If you could have any career without worrying about money, what would it be?',
    'What talent do you wish you had more time to practice?',
    'If you could be a character in any TV show, which one would you pick?',
    "What's something you're grateful for every day?",
    'If you could have a personal assistant for one task, what would it be?',
    "What's a skill you've always admired in others?",
    'If you could be a character in any classic fairy tale, who would you be?',
    "What's the most challenging book you've ever read?",
    'If you could bring any fictional character to life, who would it be?',
    "What's a place you've visited that you'd recommend to everyone?",
    "If you could have any type of pet that doesn't exist, what would it be like?",
    'What movie made you think deeply?',
    'If you could be a character in any video game, what would your role be?',
    "What's a memorable experience you've had with a stranger?",
    'If you could have any meal prepared for you right now, what would it be?',
    "What's something you've done that you never thought you could?",
    'If you could instantly learn any profession, what would it be?',
    "What's a goal you've recently achieved?",
    'If you could witness any natural phenomenon, what would it be?',
    "What's the most adventurous thing you've done in the last year?",
    'If you could have a conversation with any artist, who would you choose?',
    "What's a historical period you find fascinating?",
    'If you could have any view from your bedroom window, what would it overlook?',
    "What's a life lesson you learned from a family member?",
    'If you could change one law, what would it be?',
    "What place you've never been to but would love to explore?",
    'If you could master any form of dance, what style would you choose?',
    "What's a hobby you've always wanted to take up?",
    'If you could relive a specific year of your life, which one would it be?',
    'What food did you dislike as a child but enjoy now?',
    'If you could have any animal as a companion, what would it be?',
    "What's a song that always makes you feel nostalgic?",
    'If you could time travel to any decade, which one would it be?',
    "What's the most beautiful natural landscape you've seen?",
    'If you could have any fictional vehicle, what would it do?',
    "What's a memorable quote that has stuck with you?",
    'If you could become an expert in any historical period, which one would you choose?',
    "What's something you've always wanted to build or create?",
    'If you could be  a character in any animated movie, who would you be?',
    "What's a life lesson you'd like to teach future generations?"
]

// Scraped Online