export const relationship = [
    'What do you think shapes your approach to relationships?',
    'How would you describe an ideal relationship?',
    "What's your view on the concept of marriage?",
    'How do you define commitment?',
    "What do you think you'd be like as a parent?",
    'What concerns you about becoming a parent?',
    'What values do you hold dear?',
    "What's your greatest fear?",
    'When did you last feel emotional in front of someone?',
    'When did you last experience genuine happiness?',
    'How do you relate to your family?',
    'Do you think your family truly knows you?',
    "What's your relationship with your parents like?",
    'Could you describe your childhood?',
    'If you could change your upbringing, would you?',
    "Did your family's financial situation impact your upbringing?",
    'Do you believe your life was affected by race?',
    'What would your younger self think of who you are now?',
    'Without money constraints, how would you spend your days?',
    'What achievement are you most proud of?',
    "Are there aspects of your past you're ashamed of?",
    "How do you feel you've grown as a person?",
    'What do you feel still needs improvement?',
    "What's the toughest challenge you've faced?",
    'How do you view yourself?',
    'How do you feel about your gender identity?',
    'What feels challenging in your life currently?',
    'When do you feel most alive?',
    "What's the meaning of life to you?",
    'Do you believe humans are fundamentally good or evil?',
    'Is society progressing or regressing?',
    'Do you believe in love at first sight?',
    'What initially drew you to the person?',
    "How do you know when you're in love?",
    'What made you realize you were in love?',
    'When is the right time to express "I love you"?',
    'What gestures make you feel loved in relationships?',
    'How do compliments make you feel?',
    "What's your preferred love language?",
    'Do you believe in soulmates?',
    'How about the concept of twin flames?',
    "Do you think about the person when they're absent?",
    "What's a fond memory involving the person?",
    'When was your first romantic kiss?',
    'What proposal style resonates with you?',
    'How do you feel about public proposals?',
    "What's your favorite quality in the person?",
    'What do you cherish about yourself?',
    "What's your highlight of the relationship?",
    'What actions make you feel cherished?',
    'What makes you feel beautiful?',
    'How do you like celebrating your birthday?',
    'What shared interests do you think you have?',
    'Bright lights or subdued lighting?',
    'Fast-paced or slow and gentle?',
    'Taking charge or being more yielding?',
    'Morning intimacy or evening intimacy?',
    'Do you have a favorite intimate position?',
    "Are there positions you'd like to explore?",
    'What unexpected actions are arousing?',
    'Do you prefer oral or penetration?',
    'Consistent intimacy or infrequent, intense moments?',
    'Experience or inexperience, which would you choose?',
    'If you could engage with any celebrity, who?',
    'How often do you engage in self-pleasure?',
    'What do you fantasize about?',
    'Are you open to adult content?',
    'Would you consider watching it together?',
    'Do you recall a particularly steamy memory?',
    'Would you be open to public intimacy?',
    'How about incorporating restraints?',
    "What aspect of the person's body stands out?",
    'Which part of your body would you like them to explore?',
    'What kissing style do you enjoy?',
    'Do you have any particular interests?',
    'Can you share a sensual memory?',
    "Is there something you're curious about exploring?"
]

// Scraped Online